org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_name=Health Vignette
mod_id=healthvignette
mod_version=2.2.0
mod_description=Adds a customizable red overlay when low on health
mod_archives_name=HealthVignette
base_group=tomeko.healthvignette

java_version=[VERSIONED]
minecraft_version=[VERSIONED]

fabric_loader_version=0.19.5
fabric_api_version=[VERSIONED]
osl_version=0.21.0

oneconfig_version=[VERSIONED]
mod_menu_version=[VERSIONED]

stonecutter_version=0.10-alpha.8